### ISSUE TITLE
Integrate Travis CI

### ISSUE THREAD

**Issue by fishi0x01** [darcy95/mhttp#1]
I suggest to integrate [Travis CI](https://travis-ci.org/). Each commit / pull request could be automatically build and tested, which greatly helps to assure some degree of quality. Inside travis VMs, root permissions can be enabled, so I think `LD_PRELOAD` should work for mhttp's testing purposes. 

I already used travis on other projects and it is very easy to integrate with github and free for open source projects. 

What's your opinion on this?

**Comment by darcy95** [comment]
I don't know what exactly Travis CI is, but I am happy to try something new. I will come back to this discussion after I understand Travis CI.

**Comment by darcy95** [comment]
I looks something similar to Jenkins. Anyway, I think it is a cool idea. I am working on it.

**Comment by fishi0x01** [comment]
You are completely right: in this case it fits the same purpose. The advantage though is that Travis is a pure pipeline as code approach with no sysadmin overhead. Your whole build/test is defined inside a `.travis.yml` file inside the projects repository (though Jenkins also offers a pipeline as code approach via `Jenkinsfile` since v2, but you'd still have overhead of administering a Jenkins server).

If you activate the integration in GitHub/Travis, I could help by submitting a pull request with a working `.travis.yml` for the build/test.

**Comment by darcy95** [comment]
I am not familiar with both Jenkins and Travis. I, nevertheless, tried to write .travis.yml file. Please feel free to modify the file. I will learn it from you.

**Comment by fishi0x01** [comment]
Initial simple Travis tests added - considering issue closed
